[CORE_PACKAGE]
default = ['agents', 'llms', 'tools']
llm = ['llms']
agent = ['agents']
tool = ['tools']

[PACKAGE_PATH_INFO]
ROOT_PACKAGE = 'agent_universe_doe'

[SUB_CONFIG]
agent_config_path_list = ['./agents']
llm_config_path_list = ['./llms']

[SUB_CONFIG_PATH]
log_config_path = '/Users/rod/agent_universe_doe/config/log_config.toml'

[LOG_CONFIG]
log_path = '/Users/rod/agent_universe_doe/logs'
level = 'INFO'
rotation = '100 MB'
retention = '10 days'

[DB]
system_db_uri = 'sqlite:////Users/rod/agent_universe_doe/data/agent_universe.db'
request_table_name = 'request_task'
update_interval = 5
